=== bscholer/ntrip-catalog/schemas/v0.2/entries.schema.json
{
    "$id": "entries.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "version": "0.2",
    "title": "NTRIP-catalog entry",
    "description": "Definition of a list of entries",
    "type": "array",
    "items": {
        "type": "object",
        "description": "Definition of each entry in the NTRIP-catalog",
        "properties": {
            "name": {
                "type": "string",
                "description": "Use something sort but descriptive. Try to make it unique."
            },
            "description": {
                "type": "string",
                "description": "A longer description of the entry. Maybe the expansion of the accronym in the name"
            },
            "urls": {
                "type": "array",
                "description": "List of all the possible URLs that will match this entry. The URL should appear only once in the whole catalog.",
                "minItems": 1,
                "items": {
                    "type": "string",
                    "description": "Full identification of the URL, always including scheme, hostname and port. Must be all lowercase."
                }
            },
            "reference": {
                "type": "object",
                "description": "Source of the information, and extra comments if needed.",
                "properties": {
                    "url": {
                        "type": "string"
                    },
                    "comments": {
                        "type": "string"
                    }
                },
                "required": [
                    "url"
                ]
            },
            "last_update": {
                "type": "string",
                "description": "Date of the last update of this entry, in ISO 8601 format YYYY-MM-DD"
            },
            "streams": {
                "type": "array",
                "items": {
                    "type": "object",
                    "description": "Item to match a stream from the sourcetable with a CRS.",
                    "properties": {
                        "filter": {
                            "description": "Criterion to filter in the sourcetable",
                            "oneOf": [
                                {
                                    "$ref": "#/$defs/mountpoints_def"
                                },
                                {
                                    "$ref": "#/$defs/lat_lon_bboxes_def"
                                },
                                {
                                    "$ref": "#/$defs/countries_def"
                                },
                                {
                                    "type": "string",
                                    "enum": [
                                        "all"
                                    ],
                                    "description": "Matches all the streams. Use with caution."
                                }
                            ]
                        },
                        "crss": {
                            "type": "array",
                            "description": "List of CRSs for this stream. Either rover_bbox or rover_countries must be present in the elements to be able to pick one CRS from the list at a particular location.",
                            "minItems": 1,
                            "items": {
                                "type": "object",
                                "description": "Definition of a CRS and its selection filters, if any.",
                                "properties": {
                                    "id": {
                                        "type": "string",
                                        "description": "EPSG (or ESRI) identifier like EPSG:7931. Use a Geographic 3D code if defined. If not, a Geographic 2D."
                                    },
                                    "name": {
                                        "type": "string",
                                        "description": "Name of the CRS. If the field id is used, it must be the name in EPSG (or ESRI)."
                                    },
                                    "description": {
                                        "type": "string"
                                    },
                                    "epoch": {
                                        "type": [
                                            "number",
                                            "string"
                                        ],
                                        "description": "When epoch is needed, specify as number. String should be only used for \"now\", meaning the acquisition date."
                                    },
                                    "rover_bbox": {
                                        "$ref": "#/$defs/bbox",
                                        "description": "Bounding box where the rover should be. Use it when that is the only way to differenciate the CRSs"
                                    },
                                    "rover_countries": {
                                        "type": "array",
                                        "minItems": 1,
                                        "items": {
                                            "type": "string"
                                        },
                                        "description": "Country where the rover should be. Use it when that is the only way to differenciate the CRSs"
                                    }
                                },
                                "anyOf": [
                                    {
                                        "oneOf": [
                                            {
                                                "required": [
                                                    "rover_bbox"
                                                ]
                                            },
                                            {
                                                "required": [
                                                    "rover_countries"
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        "not": {
                                            "required": [
                                                "rover_bbox",
                                                "rover_countries"
                                            ]
                                        }
                                    }
                                ],
                                "required": [
                                    "name"
                                ],
                                "additionalProperties": false
                            }
                        },
                        "description": {
                            "type": "string",
                            "description": "Describe the stream with a filter and crss."
                        },
                        "comments": {
                            "type": "string",
                            "description": "Additional notes explaining why some things are done that way."
                        },
                        "extra": {
                            "type": "object",
                            "description": "Optional container in case special custom information wants to be added."
                        }
                    },
                    "required": [
                        "filter",
                        "crss"
                    ],
                    "additionalProperties": false
                }
            },
            "extra": {
                "type": "object",
                "description": "Optional container in case special custom information wants to be added."
            }
        },
        "required": [
            "name",
            "urls",
            "reference",
            "last_update",
            "streams"
        ],
        "additionalProperties": false
    },
    "$defs": {
        "bbox": {
            "type": "array",
            "minItems": 4,
            "maxItems": 4,
            "items": {
                "type": "number"
            },
            "description": "Bounding box, in degrees, with the order: West, South, East, North."
        },
        "mountpoints_def": {
            "type": "object",
            "properties": {
                "mountpoints": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    },
                    "description": "Matches the 'Mountpoint' field in the stream"
                }
            },
            "additionalProperties": false,
            "required": [
                "mountpoints"
            ]
        },
        "lat_lon_bboxes_def": {
            "type": "object",
            "properties": {
                "lat_lon_bboxes": {
                    "type": "array",
                    "description": "List of bboxes where the lat,lon of the stream should be included.",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/$defs/bbox"
                    }
                }
            },
            "additionalProperties": false,
            "required": [
                "lat_lon_bboxes"
            ]
        },
        "countries_def": {
            "type": "object",
            "properties": {
                "countries": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    },
                    "description": "Matches the 'Country Code' field in the stream"
                }
            },
            "additionalProperties": false,
            "required": [
                "countries"
            ]
        }
    }
}

=== bscholer/ntrip-catalog/data/World/pointonenav.json
[
    {
        "name": "Point One Nav",
        "description": "Point One Navigation world service",
        "urls": [
            "http://truertk.pointonenav.com:2101",
            "http://virtualrtk.pointonenav.com:2101",
            "http://truertk-us.pointonenav.com:2101",
            "http://truertk-eu.pointonenav.com:2101",
            "http://truertk-apac.pointonenav.com:2101",
            "https://truertk.pointonenav.com:2102",
            "https://virtualrtk.pointonenav.com:2102",
            "https://truertk-us.pointonenav.com:2102",
            "https://truertk-eu.pointonenav.com:2102",
            "https://truertk-apac.pointonenav.com:2102"
        ],
        "reference": {
            "url": "https://support.pointonenav.com/connect-to-polaris-rtk"
        },
        "last_update": "2025-01-29",
        "streams": [
            {
                "filter": {
                    "mountpoints": [
                        "POLARIS"
                    ]
                },
                "crss": [
                    {
                        "id": "EPSG:7912",
                        "name": "ITRF2014",
                        "epoch": "now"
                    }
                ]
            },
            {
                "filter": {
                    "mountpoints": [
                        "POLARIS_LOCAL"
                    ]
                },
                "crss": [
                    {
                        "id": "EPSG:6667",
                        "name": "JGD2011",
                        "rover_countries": [
                            "JPN"
                        ],
                        "description": "Japan"
                    },
                    {
                        "id": "EPSG:4927",
                        "name": "KGD2002",
                        "rover_countries": [
                            "KOR"
                        ],
                        "description": "South Korea"
                    },
                    {
                        "id": "EPSG:7929",
                        "name": "ETRF97",
                        "epoch": 2009.756,
                        "rover_countries": [
                            "GBR"
                        ],
                        "description": "United Kingdom"
                    },
                    {
                        "id": "EPSG:7931",
                        "name": "ETRF2000",
                        "epoch": 2010.5,
                        "rover_countries": [
                            "NLD"
                        ],
                        "description": "Netherlands"
                    },
                    {
                        "id": "EPSG:7843",
                        "name": "GDA2020",
                        "rover_countries": [
                            "AUS"
                        ],
                        "description": "Australia"
                    },
                    {
                        "id": "EPSG:4959",
                        "name": "NZGD2000",
                        "rover_countries": [
                            "NZL"
                        ],
                        "description": "New Zealand"
                    },
                    {
                        "id": "EPSG:8254",
                        "name": "NAD83(CSRS)v7",
                        "rover_countries": [
                            "CAN"
                        ],
                        "description": "Canada"
                    },
                    {
                        "id": "EPSG:6324",
                        "name": "NAD83(MA11)",
                        "rover_bbox": [
                            129.48,
                            1.64,
                            149.55,
                            23.9
                        ],
                        "description": "Guam"
                    },
                    {
                        "id": "EPSG:6321",
                        "name": "NAD83(PA11)",
                        "rover_bbox": [
                            157.47,
                            -17.56,
                            -151.27,
                            31.8
                        ],
                        "description": "Hawaii"
                    },
                    {
                        "id": "EPSG:6319",
                        "name": "NAD83(2011)",
                        "epoch": 2010.0,
                        "rover_countries": [
                            "USA"
                        ],
                        "description": "Continental USA, after Guam and Hawaii"
                    },
                    {
                        "id": "EPSG:7931",
                        "name": "ETRF2000",
                        "epoch": 2010.0,
                        "rover_bbox": [
                            -12,
                            35,
                            36,
                            72
                        ],
                        "description": "Continental Europe"
                    }
                ],
                "comments": "Polaris_local per region"
            }
        ]
    }
]

=== bscholer/ntrip-catalog/data/World/America/USA/ncdot.json
[
    {
        "name": "NCDOT",
        "description": "North Carolina CORS",
        "urls": [
            "http://207.4.96.200:2101",
            "http://rtn.nc.gov:2101"
        ],
        "reference": {
            "url": "https://ncgs.state.nc.us/pages/CORS-and-GNSS.htm#:~:text=The%20NC%20CORS%20Base%20Station%20Network%20is%20referenced%20to%20the%20NAD%2083(2011)%20datum."
        },
        "last_update": "2025-04-11",
        "streams": [
            {
                "filter": "all",
                "crss": [
                    {
                        "id": "EPSG:6319",
                        "name": "NAD83(2011)"
                    }
                ]
            }
        ]
    }
]

=== bscholer/ntrip-catalog/data/World/Americas/USA/nysnet.json
{
    "name": "NYSNet RTN",
    "description": "NYSNet Real Time Network",
    "urls": [
        "http://rtn.dot.ny.gov:8080",
        "http://rtn.dot.ny.gov:8082"
    ],
    "reference": {
        "url": "https://cors.dot.ny.gov/FAQ.htm#Mountpoint:~:text=18.%20Where%20do%20I%20find%20a%20list%20of%20mount%20points%3F",
        "comments": "Instructions to access PDF with mount points. Requires (free) account login."
    },
    "last_update": "2025-04-16",
    "streams": [
        {
            "filter": "all",
            "crss": [
                {
                    "id": "EPSG:6319",
                    "name": "NAD83(2011)",
                    "epoch": 2010.0
                }
            ],
            "comments": "CRS described in the PDF. All mountpoints use NAD83(2011) since 2019."
        }
    ]
}

=== bscholer/ntrip-catalog/data/World/Americas/USA/mncors.json
{
    "name": "MNDOT CORS",
    "description": "Minnesota DOT CORS",
    "urls": [
        "http://mncors.dot.state.mn.us:9000",
        "http://mncors.dot.state.mn.us:9002"
    ],
    "reference": {
        "url": "https://www.dot.state.mn.us/surveying/cors/mncors_faq.html",
        "comments": "Search for 'datum' on the page to find the table of mountpoints."
    },
    "last_update": "2025-03-26",
    "streams": [
        {
            "filter": {
                "mountpoints": [
                    "CMRx_NAD83(1996)",
                    "CMR_Plus_NAD83(1996)",
                    "RTCM_34_NAD83(1996)",
                    "RTCM_31_NAD83(1996)"
                ]
            },
            "crss": [
                {
                    "id": "EPSG:6782",
                    "name": "NAD83(CORS96)"
                }
            ],
            "comments": "Mountpoints for Minnesota which use NAD83(CORS96)"
        },
        {
            "filter": {
                "mountpoints": [
                    "CMRx_NAD83(2011)",
                    "CMR_Plus_NAD83(2011)",
                    "RTCM_34_NAD83(2011)",
                    "RTCM_31_NAD83(2011)",
                    "RTCM_23_NAD83(2011)",
                    "AGCMRX",
                    "AGCMRP",
                    "AGRTCM34",
                    "AGRTCM31"
                ]
            },
            "crss": [
                {
                    "id": "EPSG:6319",
                    "name": "NAD83(2011)",
                    "epoch": 2010.0
                }
            ],
            "comments": "Mountpoints for Minnesota which use NAD83(2011)"
        }
    ]
}

=== bscholer/ntrip-catalog/data/World/Americas/USA/odot.json
{
    "name": "Ohio DOT RTN",
    "description": "Ohio DOT Real Time Network",
    "urls": [
        "http://156.63.133.115:2101"
    ],
    "reference": {
        "url": "https://www.transportation.ohio.gov/working/engineering/cadd-mapping/survey/cors-rtn",
        "comments": "See the 'Data Formats' section"
    },
    "last_update": "2025-03-26",
    "streams": [
        {
            "filter": {
                "mountpoints": [
                    "ODOT_G_R_E_C_RTX_CMRx",
                    "ODOT_G_R_E_C_RTX_RTCM3",
                    "ODOT_VRS_CMR_PLUS",
                    "ODOT_VRS_CMR_X",
                    "ODOT_VRS_ODOT_Ag",
                    "ODOT_VRS_RTCM23",
                    "ODOT_VRS_RTCM3"
                ]
            },
            "crss": [
                {
                    "id": "EPSG:6319",
                    "name": "NAD83(2011)",
                    "epoch": 2010.0
                }
            ],
            "comments": "All mountpoints use NAD83(2011)"
        }
    ]
}

=== bscholer/ntrip-catalog/data/World/Oceania/AUS/mondopin.json
{
    "name": "Mondo Pin",
    "description": "Mondo Pin GNSS Correction Service",
    "urls": [
        "http://x.mondopin.com:2101"
    ],
    "reference": {
        "url": "https://www.mondopin.com/resources",
        "description": "Mondo Pin documentation. See Q&A -> The Mondo Pin guide to mountpoints"
    },
    "last_update": "2025-03-26",
    "streams": [
        {
            "filter": {
                "mountpoints": [
                    "94_VRS_MSM",
                    "94_VRS_RTCM30",
                    "94_NEAR_MSM",
                    "94_NEAR_RTCM30"
                ]
            },
            "crss": [
                {
                    "id": "EPSG:4939",
                    "name": "GDA94",
                    "epoch": 1994.0
                }
            ],
            "comments": "Mountpoints for Australia which use GDA94"
        },
        {
            "filter": {
                "mountpoints": [
                    "20_VRS_MSM",
                    "20_VRS_RTCM30",
                    "20_NEAR_MSM",
                    "20_NEAR_RTCM30"
                ]
            },
            "crss": [
                {
                    "id": "EPSG:7843",
                    "name": "GDA2020",
                    "epoch": 2020.0
                }
            ],
            "comments": "Mountpoints for Australia which use GDA2020"
        }
    ]
}

=== bscholer/ntrip-catalog/data/World/Americas/USA/utah-turn.json
[
    {
        "name": "TURN Utah",
        "description": "The Utah Reference Network (TURN)",
        "urls": [
            "http://165.239.144.5:2101",
            "http://turngps.utah.gov:2101"
        ],
        "reference": {
            "url": "https://gis.utah.gov/documentation/turn/connecting/"
        },
        "last_update": "2025-01-27",
        "streams": [
            {
                "filter": "all",
                "crss": [
                    {
                        "id": "EPSG:6319",
                        "name": "NAD83(2011)",
                        "epoch": 2010.0
                    }
                ]
            }
        ]
    }
]

=== bscholer/ntrip-catalog/data/World/Americas/USA/fprn.json
[
    {
        "name": "FPRN",
        "description": "Florida Primary Reference Network",
        "urls": [
            "http://40.121.5.206:10000",
            "http://ntrip.myfloridagps.com:10000"
        ],
        "reference": {
            "url": "https://www.fdot.gov/Geospatial/fprnfaq.shtm"
        },
        "last_update": "2024-12-09",
        "streams": [
            {
                "filter": "all",
                "crss": [
                    {
                        "id": "EPSG:6319",
                        "name": "NAD83(2011)"
                    }
                ]
            }
        ]
    }
]
